name: Quote System
services:
  db:
    image: postgres:17
    shm_size: 128mb
    environment:
      POSTGRES_DB: quotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwert123
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: